// Generated by CoffeeScript 1.9.1
var checkBrowser, filePath, js;

js = document.scripts;

filePath = js[js.length - 1].src;

checkBrowser = function() {
  var doCheck, eventName, win;
  doCheck = function() {
    var agent;
    agent = navigator.userAgent;
    if (!/MSIE [6|7|8]{1}\.0/.test(agent)) {
      return;
    }
    return window.location.href = filePath.replace(/browser\.js$/ig, 'update.html');
  };
  win = window;
  eventName = 'load';
  if (win.addEventListener) {
    return win.addEventListener(eventName, doCheck, false);
  } else if (win.attachEvent) {
    return win.attachEvent('on' + eventName, doCheck);
  } else {
    return win['on' + eventName] = doCheck;
  }
};

checkBrowser();
